# Generated by Django 4.0.4 on 2023-01-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodtracker',
            old_name='jounal_entry',
            new_name='journal_entry',
        ),
    ]
